server:
  port: 7070
  context-path: /gateway

spring:
  application:
    name: gateway-service

security:
  basic:
    enabled: false
    
zuul:
  #Service will be mapped under the /api URI
#  prefix: /gateway
#  Uncomment to disable auto-registering all services read from Eureka
  ignoredServices: '*'
  strip-prefix: true
  routes:
    userprofile:
      path: /userprofile/**
      service-id: userprofile-service
      strip-prefix: false
      sensitiveHeaders:
    auth-service: 
      path: /auth/**
      service-id: auth-service
      strip-prefix: false
      sensitiveHeaders:

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true # Get info during startup and update delta during later calls
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/

ribbon:
  eureka:
    enabled: true

#logging:
#  level:
#     org.springframework: DEBUG