spring:
  application:
    name: userprofile-service
    
server:
  port: 6060
  context-path: /userprofile

security:
  basic:
    enabled: false
  oauth2:
    resource:
      userInfoUri: http://localhost:8080/auth/secure/me
      preferTokenInfo: false

hostName: localhost

eureka:
  instance:
    hostname: ${hostName}
    prefer-ip-address: false
  client:
    registerWithEureka: true
    fetchRegistry: true # Get info during startup and update delta during later calls
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/

#logging:
#  level:
#     org.springframework.security: DEBUG