server:
  port: 8080
  context-path: /auth

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_oauth2_mysql?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
      
security:
  oauth2:
    resource:
      filter-order: 3
      
hostName: localhost

eureka:
  instance:
    hostname: ${hostName}
  client:
    registerWithEureka: true
    fetchRegistry: true # Get info during startup and update delta during later calls
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/

logging:
  level:
#     org.springframework.security.web.FilterChainProxy: DEBUG
     org.springframework.security: DEBUG