server:
  port: 8080
  context-path: /auth

spring:
  application:
    name: springboot-oauth2-mysql
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_oauth2_mysql?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
      
security:
  oauth2:
    resource:
      filter-order: 3
logging:
  level:
     org:
       springframework:
         security: DEBUG

#logging:
#  level:
#     org:
#       springframework:
#         security:
#          web:
#            FilterChainProxy: DEBUG