spring:
  application:
    name: eureka-service

server:
  port: 9090

hostName: localhost

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false # Get info during startup and update delta during later calls
  instance:
    hostname: ${hostName}
    prefer-ip-address: false